name : Unit test job
on: [workflow_dispatch]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: openmodelica/openmodelica:v1.26.5-minimal
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get -qq update
          apt-get -qq --no-install-recommends install python3 python3-pip
          pip install --break-system-packages numpy pandas
      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Install Modelica STL 4.0.0
        run: |
          echo "installPackage(Modelica, \"4.0.0+maint.om\", exactMatch=true);" > installModelicaStl.mos && omc installModelicaStl.mos
      - name: Run unit tests
        run: |
          pip3 install --break-system-packages --user .
          cd tests
          python3 -m unittest
